{
 "title": "Сервис рекламы",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Клики и показы по дням",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as impressions, day FROM impressions GROUP BY day ORDER BY day;"
    },
    {
     "rawSql": "SELECT COUNT(*) as clicks, day FROM clicks GROUP BY day ORDER BY day;"
    }
   ]
  },
  {
   "title": "Средняя конверсия по дням",
   "type": "trend",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    CASE \r\n        WHEN COUNT(i.serial_id) = 0 THEN 0\r\n        ELSE COUNT(c.serial_id) * 1.0 / COUNT(i.serial_id)\r\n    END AS conversion,\r\n    i.day\r\nFROM \r\n    impressions i\r\nLEFT JOIN \r\n    clicks c ON c.client_id = i.client_id AND c.campaign_id = i.campaign_id AND c.day = i.day\r\nGROUP BY \r\n    i.day\r\nORDER BY \r\n    i.day;\r\n"
    }
   ]
  },
  {
   "title": "Прибыль по дням",
   "type": "trend",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    i.day AS \"day\",\r\n    COALESCE(SUM(i.price), 0) AS \"impressions_spent\",\r\n    COALESCE(SUM(c.price), 0) AS \"clicks_spent\",\r\n    COALESCE(SUM(i.price), 0) + COALESCE(SUM(c.price), 0) AS \"total_spent\"\r\nFROM \r\n    impressions i\r\nLEFT JOIN \r\n    clicks c ON i.client_id = c.client_id AND i.campaign_id = c.campaign_id AND i.day = c.day\r\nGROUP BY \r\n    i.day\r\nORDER BY \r\n    i.day;\r\n"
    }
   ]
  },
  {
   "title": "Рекламных кампаний",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM campaigns LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество клиентов",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM clients LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество рекламодателей",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM advertisers LIMIT 50 "
    }
   ]
  },
  {
   "title": "Количество МЛ скоров",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM scores LIMIT 50 "
    }
   ]
  }
 ]
}